### ISSUE TITLE
Default to --dry-run?

### ISSUE THREAD

**Issue by 13rac1** [chadoe/docker-cleanup-volumes#31]
I haven't had any issues, but a potentially damaging script like this should default to `--dry-run` to avoid issues like #19. `git clean` defaults to following this practice:

```
$ git clean
fatal: clean.requireForce defaults to true and neither -i, -n nor -f given; refusing to clean
$ git clean -n
Would remove Dockerfile
Would remove docker-compose.yml
```

**Comment by 13rac1** [comment]
BTW I may have time to implement, but want your thoughts on the matter first.

**Comment by Ian-T-Price** [comment]
1) Thanks for this script - most useful

2) Absolutely this should be run as --dryrun by default, which is the first thing I did as we run in a multi-user environment.

This is my version.  It adds an --action parameter replacing --dryrun and a --help parameter

Also there's a couple of text clean-ups and enhancements.  

If you like I'll pull the code add this in and update the README.md as well.

Enjoy

[docker_cleanup_vols.sh.txt](https://github.com/chadoe/docker-cleanup-volumes/files/63990/docker_cleanup_vols.sh.txt)

**Comment by ryneeverett** [comment]
+1

**Comment by chadoe** [comment]
Sorry but I'm not going to change the default behavior. Too many systems already depend on it to just run as is. Besides that I don't think dry-run should be the default action. It would be like `rm file` would require an additional parameter to actually delete a file or `docker rm container` to require an additional parameter to delete a container.
Also the script is pretty much obsolete since Docker has built-in volume management since version 1.9.
