### ISSUE TITLE
Question about OSX

### ISSUE THREAD

**Issue by Surreal9** [chadoe/docker-cleanup-volumes#37]
When you say, in the precautions:

> Don't use with boot2docker, docker machine or any tools that use a virtual machine to run docker, unless you run the script on the virtual machine itself (meaning don't run this script or docker command from your MAC).

I'm using Docker 1.9 on OSX with docker-machine, is it safe for me to use the command provided `docker volume rm $(docker volume ls -qf dangling=true)` from my host? I did it from within the VM as you suggested, but I'm wondering if the warning is just for running your script on versions < 1.9?

**Comment by chadoe** [comment]
Hi, the warning is for using the script with boot2docker. If you use the command `docker volume rm..` you're using the built-in Docker functionality (added in Docker 1.9) instead of the script. I assume the built-in command can be safely used from your host. But I don't use boot2docker so I'm not sure.
